name: Tests

on:
    pull_request:
    push:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - 
        name: Run tests
        run: go test ./...
